#include QMK_KEYBOARD_H

enum planck_layers {
    _COLEMAK,
    _QWERTY,
    _MOUSE,
    _NAVIGATE,
    _SYMR,
    _SYML,
    _FUN,
    _NUMPAD,
    _SPECIAL,
    _SETTINGS,
    _NUM
};

// Tap Dance declarations
enum {
    TD_OS_CAPS,
};

// Tap Dance definitions
qk_tap_dance_action_t tap_dance_actions[] = {
    // Tap once for Shift, twice for Caps Lock
    [TD_OS_CAPS] = ACTION_TAP_DANCE_DOUBLE(KC_LGUI, KC_CAPS),
};

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[_COLEMAK] = LAYOUT_planck_grid(
        KC_TAB, KC_Q, KC_W, LCTL_T(KC_F), KC_P, KC_G,
        KC_J, KC_L, LCTL_T(KC_U), KC_Y, KC_SCLN, KC_BSPC,

        LCTL_T(KC_ESC), LSFT_T(KC_A), LT(6,KC_R), LT(3,KC_S), LT(4,KC_T), KC_D,
        KC_H, LT(5,KC_N), LT(2,KC_E), LT(7,KC_I), LSFT_T(KC_O), KC_QUOT,

        KC_LSFT, MT(MOD_LCTL | MOD_LGUI, KC_Z), LALT_T(KC_X), LCTL_T(KC_C), KC_V, KC_B,
        KC_K, KC_M, LCTL_T(KC_COMM), LALT_T(KC_DOT), KC_SLSH, RSFT_T(KC_ENT),

        LT(9,KC_NO), KC_NO, KC_NO, KC_LGUI, LT(10,KC_ENT), KC_BSPC,
        LCTL(KC_SCLN), LT(8,KC_SPC), TD(TD_OS_CAPS), KC_NO, KC_NO, KC_LGUI
        ),

	[_QWERTY] = LAYOUT_planck_grid(
        KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T,
        KC_Y, KC_U, KC_I, KC_O, KC_P, KC_BSPC,

        LCTL_T(KC_ESC), LSFT_T(KC_A), LT(6,KC_S), LT(3,KC_D), LT(4,KC_F), KC_G,
        KC_H, LT(5,KC_J), LT(2,KC_K), LT(7,KC_L), LSFT_T(KC_SCLN), KC_QUOT,

        KC_LSFT, MT(MOD_LCTL | MOD_LGUI, KC_Z), LALT_T(KC_X), LCTL_T(KC_C), KC_V, KC_B,
        KC_N, KC_M, LCTL_T(KC_COMM), LALT_T(KC_DOT), KC_SLSH, RSFT_T(KC_ENT),

        LT(9,KC_NO), KC_NO, KC_NO, KC_LGUI, LT(10,KC_ENT), KC_BSPC,
        LCTL(KC_SCLN), LT(8,KC_SPC), TD(TD_OS_CAPS), KC_NO, KC_NO, KC_LGUI
        ),

	[_MOUSE] = LAYOUT_planck_grid(KC_TRNS, KC_TRNS, KC_TRNS, KC_MS_U, KC_WH_U, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_MS_L, KC_MS_D, KC_MS_R, KC_TRNS, KC_TRNS, KC_BTN1, KC_NO, KC_BTN2, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_WH_D, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),

	[_NAVIGATE] = LAYOUT_planck_grid(KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_PGUP, KC_HOME, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_LSFT, KC_LCTL, KC_NO, KC_LGUI, KC_TRNS, KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_PGDN, KC_END, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),

	[_SYMR] = LAYOUT_planck_grid(
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_PIPE, KC_UNDS, KC_PLUS, KC_DQUOT, KC_EQL, KC_TRNS,

        KC_TRNS, KC_CIRC, KC_ASTR, KC_AMPR, KC_NO, KC_TRNS,
        KC_HASH, KC_MINS, KC_SLSH, KC_QUO, KC_DLR, KC_TRNS,
        
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TILD, KC_BSLS, KC_GRV, KC_TRNS, KC_TRNS,

        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS
        ),

	[_SYML] = LAYOUT_planck_grid(KC_TRNS, KC_TRNS, KC_COLN, KC_LT, KC_GT, KC_SCLN, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_LCBR, KC_RCBR, KC_LPRN, KC_RPRN, KC_AT, KC_TRNS, KC_NO, KC_EQL, KC_PLUS, KC_PERC, KC_TRNS, KC_TRNS, KC_TRNS, KC_EXLM, KC_LBRC, KC_RBRC, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),

	[_FUN] = LAYOUT_planck_grid(KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_F7, KC_F8, KC_F9, KC_F10, KC_TRNS, KC_TRNS, KC_TRNS, KC_NO, KC_LCTL, KC_TRNS, KC_TRNS, KC_TRNS, KC_F4, KC_F5, KC_F6, KC_F11, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_F1, KC_F2, KC_F3, KC_F12, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),

	[_NUMPAD] = LAYOUT_planck_grid(KC_TRNS, KC_PSLS, KC_7, KC_8, KC_9, KC_PPLS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_P0, KC_1, KC_2, KC_3, KC_PMNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_PAST, KC_4, KC_5, KC_6, KC_PEQL, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),

	[_SPECIAL] = LAYOUT_planck_grid(
            KC_TRNS, KC_TRNS, KC_TRNS, KC_COLN, KC_ESC, KC_TRNS,
            DF(1), KC_TRNS, KC_TRNS, KC_TRNS, KC_DEL, KC_BSPC,

            KC_TRNS, LCTL(KC_B), KC_PERC, KC_SLSH, KC_ENT, KC_TRNS,
            DF(2), KC_LGUI, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,

            KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_EXLM, KC_TRNS,
            DF(0), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,

            KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TAB, KC_TRNS,
            KC_TRNS, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS
            ),

	[_SETTINGS] = LAYOUT_planck_grid(KC_NO, RESET, DEBUG, KC_NO, RGB_TOG, RGB_HUD, RGB_HUI, RGB_SAD, RGB_SAI, RGB_VAD, RGB_VAI, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_VOLD, KC_VOLU, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_BRID, KC_BRIU, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO),

	[_NUM] = LAYOUT_planck_grid(KC_TRNS, LCTL(KC_1), LCTL(KC_2), LCTL(KC_3), LCTL(KC_4), LCTL(KC_5), LCTL(KC_6), LCTL(KC_7), LCTL(KC_8), LCTL(KC_9), KC_TRNS, KC_TRNS, KC_TRNS, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_TRNS, KC_TRNS, KC_EXLM, KC_AT, KC_HASH, KC_DLR, KC_PERC, KC_CIRC, KC_AMPR, KC_ASTR, KC_LPRN, KC_RPRN, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS)
};

